import { Project } from "@/types/project";
import { Timestamp } from "firebase/firestore";

// Create a dummy timestamp for the dummy projects
const dummyTimestamp = Timestamp.fromDate(new Date());

/**
 * Dummy projects data to be used as fallback when no real projects are available
 * These projects use existing images from the public folder
 */
export const dummyProjects: Project[] = [
  {
    id: "dummy-1",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Carmen Retreat",
    location: "Tulum, Mexico",
    description:
      "A private wellness sanctuary suspended above the underground rivers of the Riviera Maya.",
    description2: "Set between the sacred ruins of Tulum and the vibrant shores of Cancun.",
    designDescription:
      "Natural stone, textured wood, raw lime, woven palm. Each element was chosen to echo the soul of the land.",
    designSubtitle: "Wellness Sanctuary",
    designTitle: "Carmen Retreat",
    isSoon: false,
    mainImageUrl: "/images/pages/home/design1.png",
    previewImageUrl: "/images/pages/home/design1.png",
    fullWidthImageUrl: "/images/pages/home/design1.png",
    secondFullWidthImageUrl: "/images/pages/home/design1.png",
    secondImageUrl: "/images/pages/home/design1.png",
    footerFullWidthImageUrl: "/images/pages/home/design1.png",
    halfImage1Url: "/images/pages/home/design1.png",
    halfImage1Text: "Open Spaces, Quiet Paths",
    halfImage1Subtext: "Flowing terraces open gently to the jungle",
    halfImage2Url: "/images/pages/home/design1.png",
    halfImage2Text: "Letting Nature Take the Lead",
    halfImage2Subtext: "Architecture that doesn't dominate",
    secondHalfImage1Url: "/images/pages/home/design1.png",
    secondHalfImage1Text: "Sacred Geometry",
    secondHalfImage2Url: "/images/pages/home/design1.png",
    secondHalfImage2Text: "Natural Materials",
    threeImages1Url: "/images/pages/home/design1.png",
    threeImages2Url: "/images/pages/home/design1.png",
    threeImages3Url: "/images/pages/home/design1.png",
  },
  {
    id: "dummy-2",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Ocean House",
    location: "Malibu, California",
    description:
      "A modern coastal retreat that blurs the boundaries between indoor and outdoor living.",
    description2: "Designed to capture the essence of California's coastal lifestyle.",
    designDescription:
      "Clean lines, natural materials, and expansive glass create a seamless connection to the ocean.",
    designSubtitle: "Coastal Living",
    designTitle: "Ocean House",
    isSoon: false,
    mainImageUrl: "/images/pages/home/design2.png",
    previewImageUrl: "/images/pages/home/design2.png",
    fullWidthImageUrl: "/images/pages/home/design2.png",
    secondFullWidthImageUrl: "/images/pages/home/design2.png",
    secondImageUrl: "/images/pages/home/design2.png",
    footerFullWidthImageUrl: "/images/pages/home/design2.png",
    halfImage1Url: "/images/pages/home/design2.png",
    halfImage1Text: "Ocean Views",
    halfImage1Subtext: "Panoramic windows frame the Pacific",
    halfImage2Url: "/images/pages/home/design2.png",
    halfImage2Text: "Natural Light",
    halfImage2Subtext: "Designed to maximize daylight",
    secondHalfImage1Url: "/images/pages/home/design2.png",
    secondHalfImage1Text: "Outdoor Living",
    secondHalfImage2Url: "/images/pages/home/design2.png",
    secondHalfImage2Text: "Seamless Integration",
    threeImages1Url: "/images/pages/home/design2.png",
    threeImages2Url: "/images/pages/home/design2.png",
    threeImages3Url: "/images/pages/home/design2.png",
  },
  {
    id: "dummy-3",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Mountain Lodge",
    location: "Aspen, Colorado",
    description: "A rustic yet refined mountain retreat that honors the natural landscape.",
    description2: "Built with local materials and designed to withstand the elements.",
    designDescription:
      "Heavy timber construction, stone foundations, and large windows create a warm, inviting space.",
    designSubtitle: "Mountain Retreat",
    designTitle: "Mountain Lodge",
    isSoon: false,
    mainImageUrl: "/images/pages/home/design3.png",
    previewImageUrl: "/images/pages/home/design3.png",
    fullWidthImageUrl: "/images/pages/home/design3.png",
    secondFullWidthImageUrl: "/images/pages/home/design3.png",
    secondImageUrl: "/images/pages/home/design3.png",
    footerFullWidthImageUrl: "/images/pages/home/design3.png",
    halfImage1Url: "/images/pages/home/design3.png",
    halfImage1Text: "Rustic Elegance",
    halfImage1Subtext: "Timber and stone construction",
    halfImage2Url: "/images/pages/home/design3.png",
    halfImage2Text: "Mountain Views",
    halfImage2Subtext: "Panoramic windows to the peaks",
    secondHalfImage1Url: "/images/pages/home/design3.png",
    secondHalfImage1Text: "Cozy Interiors",
    secondHalfImage2Url: "/images/pages/home/design3.png",
    secondHalfImage2Text: "Natural Materials",
    threeImages1Url: "/images/pages/home/design3.png",
    threeImages2Url: "/images/pages/home/design3.png",
    threeImages3Url: "/images/pages/home/design3.png",
  },
  {
    id: "dummy-4",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Urban Loft",
    location: "New York, NY",
    description: "A contemporary loft space that maximizes natural light and city views.",
    description2: "Industrial elements meet modern comfort in the heart of Manhattan.",
    designDescription:
      "Exposed brick, steel beams, and floor-to-ceiling windows create an open, airy feel.",
    designSubtitle: "Urban Living",
    designTitle: "Urban Loft",
    isSoon: false,
    mainImageUrl: "/images/pages/home/design4.png",
    previewImageUrl: "/images/pages/home/design4.png",
    fullWidthImageUrl: "/images/pages/home/design4.png",
    secondFullWidthImageUrl: "/images/pages/home/design4.png",
    secondImageUrl: "/images/pages/home/design4.png",
    footerFullWidthImageUrl: "/images/pages/home/design4.png",
    halfImage1Url: "/images/pages/home/design4.png",
    halfImage1Text: "Industrial Design",
    halfImage1Subtext: "Exposed brick and steel beams",
    halfImage2Url: "/images/pages/home/design4.png",
    halfImage2Text: "City Views",
    halfImage2Subtext: "Floor-to-ceiling windows",
    secondHalfImage1Url: "/images/pages/home/design4.png",
    secondHalfImage1Text: "Open Plan",
    secondHalfImage2Url: "/images/pages/home/design4.png",
    secondHalfImage2Text: "Modern Comfort",
    threeImages1Url: "/images/pages/home/design4.png",
    threeImages2Url: "/images/pages/home/design4.png",
    threeImages3Url: "/images/pages/home/design4.png",
  },
  {
    id: "dummy-5",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Garden Villa",
    location: "Tuscany, Italy",
    description:
      "A traditional Italian villa restored with modern amenities and sustainable practices.",
    description2: "Surrounded by olive groves and vineyards in the heart of Tuscany.",
    designDescription:
      "Traditional stone construction with modern updates, featuring local materials and craftsmanship.",
    designSubtitle: "Italian Villa",
    designTitle: "Garden Villa",
    isSoon: false,
    mainImageUrl: "/images/pages/home/project1.png",
    previewImageUrl: "/images/pages/home/project1.png",
    fullWidthImageUrl: "/images/pages/home/project1.png",
    secondFullWidthImageUrl: "/images/pages/home/project1.png",
    secondImageUrl: "/images/pages/home/project1.png",
    footerFullWidthImageUrl: "/images/pages/home/project1.png",
    halfImage1Url: "/images/pages/home/project1.png",
    halfImage1Text: "Traditional Stone",
    halfImage1Subtext: "Local materials and craftsmanship",
    halfImage2Url: "/images/pages/home/project1.png",
    halfImage2Text: "Garden Views",
    halfImage2Subtext: "Olive groves and vineyards",
    secondHalfImage1Url: "/images/pages/home/project1.png",
    secondHalfImage1Text: "Modern Amenities",
    secondHalfImage2Url: "/images/pages/home/project1.png",
    secondHalfImage2Text: "Sustainable Design",
    threeImages1Url: "/images/pages/home/project1.png",
    threeImages2Url: "/images/pages/home/project1.png",
    threeImages3Url: "/images/pages/home/project1.png",
  },
  {
    id: "dummy-6",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Desert Oasis",
    location: "Palm Springs, CA",
    description:
      "A mid-century modern home that celebrates the desert landscape and architectural heritage.",
    description2:
      "Clean lines, natural materials, and indoor-outdoor living in the California desert.",
    designDescription:
      "Mid-century modern design with contemporary updates, featuring glass walls and natural stone.",
    designSubtitle: "Desert Modern",
    designTitle: "Desert Oasis",
    isSoon: true, // This one is marked as "coming soon" for the DiscoverProjects section
    mainImageUrl: "/images/pages/home/project2.png",
    previewImageUrl: "/images/pages/home/project2.png",
    fullWidthImageUrl: "/images/pages/home/project2.png",
    secondFullWidthImageUrl: "/images/pages/home/project2.png",
    secondImageUrl: "/images/pages/home/project2.png",
    footerFullWidthImageUrl: "/images/pages/home/project2.png",
    halfImage1Url: "/images/pages/home/project2.png",
    halfImage1Text: "Mid-Century Modern",
    halfImage1Subtext: "Clean lines and natural materials",
    halfImage2Url: "/images/pages/home/project2.png",
    halfImage2Text: "Desert Landscape",
    halfImage2Subtext: "Indoor-outdoor living",
    secondHalfImage1Url: "/images/pages/home/project2.png",
    secondHalfImage1Text: "Glass Walls",
    secondHalfImage2Url: "/images/pages/home/project2.png",
    secondHalfImage2Text: "Natural Stone",
    threeImages1Url: "/images/pages/home/project2.png",
    threeImages2Url: "/images/pages/home/project2.png",
    threeImages3Url: "/images/pages/home/project2.png",
  },
  {
    id: "dummy-7",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Forest Cabin",
    location: "Portland, Oregon",
    description: "A sustainable cabin that blends seamlessly with the Pacific Northwest forest.",
    description2: "Built with reclaimed materials and designed for minimal environmental impact.",
    designDescription:
      "Sustainable design with reclaimed wood, solar panels, and rainwater collection systems.",
    designSubtitle: "Eco-Friendly",
    designTitle: "Forest Cabin",
    isSoon: true, // This one is also marked as "coming soon"
    mainImageUrl: "/images/pages/home/project3.png",
    previewImageUrl: "/images/pages/home/project3.png",
    fullWidthImageUrl: "/images/pages/home/project3.png",
    secondFullWidthImageUrl: "/images/pages/home/project3.png",
    secondImageUrl: "/images/pages/home/project3.png",
    footerFullWidthImageUrl: "/images/pages/home/project3.png",
    halfImage1Url: "/images/pages/home/project3.png",
    halfImage1Text: "Reclaimed Materials",
    halfImage1Subtext: "Sustainable construction",
    halfImage2Url: "/images/pages/home/project3.png",
    halfImage2Text: "Forest Integration",
    halfImage2Subtext: "Blends with natural surroundings",
    secondHalfImage1Url: "/images/pages/home/project3.png",
    secondHalfImage1Text: "Solar Power",
    secondHalfImage2Url: "/images/pages/home/project3.png",
    secondHalfImage2Text: "Rainwater Collection",
    threeImages1Url: "/images/pages/home/project3.png",
    threeImages2Url: "/images/pages/home/project3.png",
    threeImages3Url: "/images/pages/home/project3.png",
  },
  {
    id: "dummy-8",
    createdAt: dummyTimestamp,
    updatedAt: dummyTimestamp,
    title: "Skyline Penthouse",
    location: "Miami, Florida",
    description: "A luxury penthouse with panoramic ocean and city views in the heart of Miami.",
    description2: "Modern design meets tropical luxury in this exclusive high-rise residence.",
    designDescription:
      "Floor-to-ceiling windows, premium finishes, and outdoor terraces create the ultimate urban oasis.",
    designSubtitle: "Luxury Living",
    designTitle: "Skyline Penthouse",
    isSoon: true, // This one is also marked as "coming soon"
    mainImageUrl: "/images/pages/home/design4.png",
    previewImageUrl: "/images/pages/home/design4.png",
    fullWidthImageUrl: "/images/pages/home/design4.png",
    secondFullWidthImageUrl: "/images/pages/home/design4.png",
    secondImageUrl: "/images/pages/home/design4.png",
    footerFullWidthImageUrl: "/images/pages/home/design4.png",
    halfImage1Url: "/images/pages/home/design4.png",
    halfImage1Text: "Ocean Views",
    halfImage1Subtext: "Panoramic windows to the Atlantic",
    halfImage2Url: "/images/pages/home/design4.png",
    halfImage2Text: "Tropical Luxury",
    halfImage2Subtext: "Modern design meets Miami style",
    secondHalfImage1Url: "/images/pages/home/design4.png",
    secondHalfImage1Text: "Outdoor Terraces",
    secondHalfImage2Url: "/images/pages/home/design4.png",
    secondHalfImage2Text: "Premium Finishes",
    threeImages1Url: "/images/pages/home/design4.png",
    threeImages2Url: "/images/pages/home/design4.png",
    threeImages3Url: "/images/pages/home/design4.png",
  },
];

/**
 * Get dummy projects for the gallery (non-coming soon projects)
 */
export function getDummyGalleryProjects(): Project[] {
  return dummyProjects.filter((project) => !project.isSoon);
}

/**
 * Get dummy projects for the discover section (coming soon projects)
 */
export function getDummyDiscoverProjects(): Project[] {
  return dummyProjects.filter((project) => project.isSoon);
}
